from cogito.core.exceptions import BadRequestError

__all__ = ["BadRequestError"]
